name: build-pr
on:
  pull_request_target:
  
    # We don't need to run builds when these files change
    paths-ignore:
      - '.github/**'
      - 'README.me'
      - 'Dockerfile'
      - '.dockerignore'
    branches:
      - main

    #Ensure we build when a review is requested (as we don't build w/o a review)
    types: [review_requested, synchronize]

# Ensure that if there are multiple builds for a PR only 1 is queued
# Example: 1st commit in PR starts a build then 2-9 commits come in during the first build.
#          This makes it so that only commit 9 is enqueued to build rather than builds for 2-9 all being queued
concurrency: 
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true #only 1 build at a time per PR
jobs:
  build:
    runs-on: pr
    if: | 
       github.event.pull_request.requested_reviewers[0] != null
    steps:
      - name: Get date for artifacts
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H%M')"
      - uses: actions/checkout@v2
        name: checkout (pull request)
        with:
          clean: false
          # pull requests require explicitly using the pr sha
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build rg351P
        run: |
            set -e
            make docker-RG351P
      - name: Build rg351V
        run: |
            set -e
            make docker-RG351P
      - name: Cleanup system artifacts (no .img in PR builds)
        run: |
            set -e
            rm -rf release/aarch64/RG351*/*.system*
            #PR's builds only include the .tar for speed
            rm -rf release/aarch64/RG351*/*.img.gz*
      - name: Archive RG351V-PR-${{ github.event.pull_request.number }}
        uses: actions/upload-artifact@v2
        with:
          name: RG351V-PR-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.head.sha }}
          path: |
            release/aarch64/RG351V/
      - name: Archive RG351P-PR-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.ref }}-
        uses: actions/upload-artifact@v2
        with:
          name: RG351P-PR-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.head.sha }}
          path: |
            release/aarch64/RG351P/
